using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MedSet.RESTAPI
{
	public class RegisterLoginModel
	{
		// User ID alloted by our app.
		public string user_id;
		// Auth token generated by our app.
		public string auth_token;
		// Difference between the AuthToken.Timestamp and now in seconds.
		public long seconds;

		public RegisterLoginModel(string user_id, string auth_token, long seconds)
		{
			this.seconds = seconds;
			this.user_id = user_id;
			this.auth_token = auth_token;
		}

		public RegisterLoginModel() { }
	}
}